package io.bf2fc6cc711aee1a0c2a.execution.tasks;

public enum TaskType {

    CREATE_REGISTRY,
    SCHEDULE_REGISTRY,
    PROVISION_REGISTRY_TENANT,
    REGISTRY_HEARTBEAT,

    CREATE_REGISTRY_DEPLOYMENT,
    REGISTRY_DEPLOYMENT_HEARTBEAT,

}
