name: Build and Test
on:
  push:
    branches:
      - main
      - feat/hackathon # TODO Remove
  pull_request:
    branches:
      - main
      - feat/hackathon # TODO Remove

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  IMAGE_TAG: latest

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'bf2fc6cc711aee1a0c2a'
    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v1

      # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare Build of SRS Fleet Manager
        run: |
          cd "${{ github.workspace }}"

      - name: Run linter
        run: |
          .github/scripts/install-tools.sh
          .github/scripts/validate-files.sh

      - name: Build SRS Fleet Manager in dev mode
        env:
          EXTRA_ARGS: -DskipGroups=none
        run: |
          make dev-build

      - name: Build SRS Fleet Manager
        env:
          EXTRA_ARGS: -DskipGroups=none
        run: |
          APICURIO_REGISTRY_BRANCH="master" make pr-check

      - name: Set Image Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "IMAGE_TAG=latest-snapshot" >> $GITHUB_ENV

      - name: Login to DockerHub Registry
        if: github.event_name == 'push'
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build and Publish Docker Image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ./core/
          file: ./core/src/main/docker/Dockerfile.legacy-jar
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: |
            docker.io/apicurio/apicurio-registry-fleet-manager:${{env.IMAGE_TAG}}
            quay.io/apicurio/apicurio-registry-fleet-manager:${{env.IMAGE_TAG}}
