name: Build and Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'bf2fc6cc711aee1a0c2a'
    steps:

      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          architecture: x64

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Build Apicurio Registry Tenant Manager
        run: |
          cd "${{ github.workspace }}/.."
          git clone https://github.com/Apicurio/apicurio-registry.git -o upstream apicurio-registry.git
          cd apicurio-registry.git
          git checkout multitenant-sr-demo
          make tenant-manager-build

      - name: Prepare Build of SRS Fleet Manager
        run: |
          cd "${{ github.workspace }}"

      - name: Build SRS Fleet Manager
        run: |
          mvn -B install

      - name: Build SRS Fleet Manager - Docker
        run: |
          mvn -B install -DskipTests -Dquarkus.container-image.build=true
