name: Build and Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'bf2fc6cc711aee1a0c2a'
    steps:

      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          architecture: x64

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Prepare Build of SRS Fleet Manager
        run: |
          cd "${{ github.workspace }}"

      - name: Build SRS Fleet Manager in dev mode
        env:
          EXTRA_ARGS: -DskipGroups=none
        run: |
          make dev-build

      - name: Build SRS Fleet Manager
        env:
          EXTRA_ARGS: -DskipGroups=none
        run: |
          make pr-check

      - name: Build SRS Fleet Manager - Docker
        # TODO move this to Makefile and update build scripts to share logic?
        run: |
          mvn -B install -DskipTests -Dquarkus.container-image.build=true -pl core
