name: Code Scan
on:
  pull_request:
    branches:
      #- main
      - code-scanning

jobs:
  code-scan:
    name: Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Build Dendencies
        run: APICURIO_REGISTRY_BRANCH="main" make build-tenant-manager-deps

      - name: Analyze
        run: mvn verify -DskipTests -Pcode-scan --no-transfer-progress

      - name: SpotBugs
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'

      - name: PMD
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'
