name: Trivy Image Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  quarkus-dist:
    name: Docker vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.6.2
        with:
          # TODO: check which image tags we want to scan
          image-ref: 'quay.io/apicurio/apicurio-registry-fleet-manager:latest-snapshot'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
