name: Trivy Image Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  call-image-scan:
    uses: Apicurio/apicurio-gh-workflows/.github/workflows/image-scan.yaml@main
    with:
      image: quay.io/apicurio/apicurio-registry-fleet-manager:latest-snapshot
