name: Validate OpenAPI schema with Spectral
on:
  workflow_call: { }
  pull_request:
    branches:
      - main
    paths:
      - core/src/main/resources/srs-fleet-manager.json

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      # sets up node, used to pull RHOAS ruleset package
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install RHOAS Guidlines linter
        run: npm i @rhoas/spectral-ruleset
      - name: Validate OpenAPI schema with Spectral and RHOAS Guidelines
        run: npx rhoasapi lint ./core/src/main/resources/srs-fleet-manager.json
