name: Dispatch OpenAPI File Change event
on:
  push:
    branches:
      - main
    paths:
      - core/src/main/resources/srs-fleet-manager.json

jobs:
  validate:
    uses: ./.github/workflows/openapi_lint.yaml
  dispatch:
    needs: validate
    env:
      APP_SERVICES_CI_TOKEN: ${{ secrets.APP_SERVICES_CI_TOKEN }}
    strategy:
      matrix:
        repo: [ "redhat-developer/app-services-sdk-go", "redhat-developer/app-services-sdk-js", "redhat-developer/app-services-sdk-java", "redhat-developer/app-services-sdk-core" ]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bf2fc6cc711aee1a0c2a'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ env.APP_SERVICES_CI_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: openapi-spec-change
          client-payload: '{ "id": "srs-mgmt/v1", "download_url":"https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/main/core/src/main/resources/srs-fleet-manager.json"}'
