name: Validate OpenAPI schema with Spectral
on:
  workflow_call: { }
  pull_request:
    branches:
      - main
      - mas-sr
    paths:
      - core/src/main/resources/srs-fleet-manager.json

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      # sets up node, used to pull RHOAS ruleset package
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install RHOAS Guidlines linter
        run: |
          npm i @rhoas/spectral-ruleset
          echo 'extends: "@rhoas/spectral-ruleset"' > .spectral.yaml
      - name: Validate OpenAPI schema with Spectral and RHOAS Guidelines
        run: npx rhoasapi lint ./core/src/main/resources/srs-fleet-manager.json
      - name: Cleanup
        run: |
          rm .spectral.yaml
