name: Update Apicurio mas-sr Dependencies
on:
  schedule:
    - cron: '0 8 * * 1-5' #At 08:00 on every day-of-week from Monday through Friday.
  workflow_dispatch: #manual trigger
jobs:
  check:
    name: Check and update Apicurio dependencies from mas-sr branch
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'bf2fc6cc711aee1a0c2a'
    steps:

      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          architecture: x64

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Prepare Build of SRS Fleet Manager
        run: |
          cd "${{ github.workspace }}"
        
      - name: Install jq and yq
        run: |
          sudo apt-get install jq
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Run version update
        run: make update-tenant-manager-dep-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Apicurio dependencies
          title: Update Apicurio dependencies
          body: |
            - Apicurio Dependency updates from mas-sr

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-apicurio-dependencies
          delete-branch: true