name: Update Apicurio mas-sr Dependencies
on:
  schedule:
    - cron: '0 8 * * 1-5' #At 08:00 on every day-of-week from Monday through Friday.
  workflow_dispatch: #manual trigger
jobs:
  check:
    name: Check and update Apicurio dependencies from mas-sr branch
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bf2fc6cc711aee1a0c2a'
    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Prepare Build of SRS Fleet Manager
        run: |
          cd "${{ github.workspace }}"
        
      - name: Install jq and yq
        run: |
          sudo apt-get install jq
          pip3 install yq

      - name: Run version update
        run: make update-tenant-manager-dep-version

      - name: Build SRS Fleet Manager
        env:
          EXTRA_ARGS: -DskipGroups=none
        run: |
          make pr-check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Apicurio dependencies
          title: Update Apicurio dependencies
          body: |
            - Apicurio Dependency updates from mas-sr

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-apicurio-dependencies
          delete-branch: true

      - name: Notify of version update failure
        if: ${{ failure() }}
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
